version: '3'
services:
    mybaseproject:
        build: .
        image: mybaseprojectapi
        ports:
          - "8080:8080"
          - "8081:8081"
        volumes:
          - ../logs:/MyBaseProject.Api/logs
        networks:
          - mybaseprojectnet
networks:
  mybaseprojectnet:
    external: true
